site_name: Aurora Compiler
repo_url: https://github.com/PrestonHager/AuroraCompiler.git
site_author: PrestonHager
pages:
- ["index.md", "Plan"]
- ["lexer.md", "Lexer"]
- ["parser.md", "Parser"]
- ["generator.md", "Generator"]
- ["syntax.md", "Syntax"]
