; generated by Aurora Compiler by Preston Hager
; https://github.com/PrestonHager/AuroraCompiler
[BITS 32]

%include "_aurora_io"
%include "fake"
; print a simple message.
; Arguments: [<ASTValue STRING: `Somewhere over the rainbow!`, <ASTValue STRING: `Hi`]
call print
