; generated by Aurora Compiler by Preston Hager
; https://github.com/PrestonHager/AuroraCompiler
; UUID: 50ffb7850f1fa8a0f73cf779d3d5b2cd
[BITS 32]

; print a simple message.
; Arguments: [<ASTValue STRING: `Somewhere over the rainbow!`>, <ASTValue STRING: `Hi`>]
mov [_aurora_arg_buffer+4], DWORD _aurora_50ffb7850f1fa8a0f73cf779d3d5b2cd_string_0
mov [_aurora_arg_buffer+8], DWORD _aurora_50ffb7850f1fa8a0f73cf779d3d5b2cd_string_1
call print

_aurora_arg_buffer times 32 dq 0
%include "C:\Users\discover\Documents\PrestonDeveloping\AuroraCompiler\bin\libraries\_aurora_io.asm"
_aurora_50ffb7850f1fa8a0f73cf779d3d5b2cd_string_0 db "Somewhere over the rainbow!", 0
_aurora_50ffb7850f1fa8a0f73cf779d3d5b2cd_string_1 db "Hi", 0