; generated by Aurora Compiler by Preston Hager
; https://github.com/PrestonHager/AuroraCompiler
; UUID: 52beeb8e230fa40b883f93e166ffe3
[BITS 32]

; print a simple message.
; Arguments: [<ASTValue STRING: `Somewhere over the rainbow!`>, <ASTValue STRING: `Hi`>]
mov [_aurora_arg_buffer+4], DWORD _aurora_52beeb8e230fa40b883f93e166ffe3_string_0
mov [_aurora_arg_buffer+8], DWORD _aurora_52beeb8e230fa40b883f93e166ffe3_string_1
call print

_aurora_arg_buffer times 32 dq 0
%include "/Users/prestonhager/Documents/AuroraCompiler/bin/libraries/_aurora_io.asm"
_aurora_52beeb8e230fa40b883f93e166ffe3_string_0 db "Somewhere over the rainbow!", 0
_aurora_52beeb8e230fa40b883f93e166ffe3_string_1 db "Hi", 0