; generated by Aurora Compiler by Preston Hager
; https://github.com/PrestonHager/AuroraCompiler
; UUID: b6a9d52b93071075dab0dcc0b72bc416
[BITS 32]

; Testing Variable Definition
; Arguments: [<ASTValue STRING: `Variable`>, <ASTValue STRING: ` Tests`>]
mov [_aurora_arg_buffer+4], DWORD _aurora_b6a9d52b93071075dab0dcc0b72bc416_string_0
mov [_aurora_arg_buffer+8], DWORD _aurora_b6a9d52b93071075dab0dcc0b72bc416_string_1
call println
; Define a variable.
; and print it out.
; Arguments: [<ASTValue VARIABLE: `greeting`>]
call println
; Now for the numbers.
mov eax, 15
mov [_b6a9d52b93071075dab0dcc0b72bc416_age], eax
; and see if it prints.
; Arguments: [<ASTValue VARIABLE: `str`>, <ASTNode(2) FUNCTION: [<ASTNode(1) ARGUMENTS: [<ASTValue VARIABLE: `age`>]>, <ASTValue NAME: `str`>]>]
call println

_aurora_arg_buffer times 32 dq 0
%include "C:\Users\discover\Documents\PrestonDeveloping\AuroraCompiler\bin\libraries\_aurora_io.asm"
%include "C:\Users\discover\Documents\PrestonDeveloping\AuroraCompiler\bin\libraries\_aurora_string.asm"
_aurora_b6a9d52b93071075dab0dcc0b72bc416_string_0 db "Variable", 0
_aurora_b6a9d52b93071075dab0dcc0b72bc416_string_1 db " Tests", 0
_b6a9d52b93071075dab0dcc0b72bc416_greeting db "NULL"
_b6a9d52b93071075dab0dcc0b72bc416_age dd 0