; generated by Aurora Compiler by Preston Hager
; https://github.com/PrestonHager/AuroraCompiler
; UUID: 926c26dd110ca422c302616e2d03c032
[BITS 32]

; Testing Variable Definition
; Arguments: [<ASTValue STRING: `Variable`>, <ASTValue STRING: ` Tests`>]
mov [_aurora_arg_buffer+4], DWORD _aurora_926c26dd110ca422c302616e2d03c032_string_0
mov [_aurora_arg_buffer+8], DWORD _aurora_926c26dd110ca422c302616e2d03c032_string_1
call println
; Define a variable.
; and print it out.
; Arguments: [<ASTValue VARIABLE: `greeting`>]
mov [_aurora_arg_buffer+4], DWORD _926c26dd110ca422c302616e2d03c032_greeting
call println
; Now for the numbers.
mov eax, 15
mov [_926c26dd110ca422c302616e2d03c032_age], eax
; and see if it prints.
; Arguments: [<ASTValue VARIABLE: `age`>]
mov [_aurora_arg_buffer+4], DWORD _926c26dd110ca422c302616e2d03c032_age
call println

_aurora_arg_buffer times 32 dq 0
%include "/Users/prestonhager/Documents/AuroraCompiler/bin/libraries/_aurora_io.asm"
%include "/Users/prestonhager/Documents/AuroraCompiler/bin/libraries/_aurora_string.asm"
_aurora_926c26dd110ca422c302616e2d03c032_string_0 db "Variable", 0
_aurora_926c26dd110ca422c302616e2d03c032_string_1 db " Tests", 0
_926c26dd110ca422c302616e2d03c032_greeting db "Hello!", 0
_926c26dd110ca422c302616e2d03c032_age dd 0